- name: Set up servers
  hosts: all
  become: yes
  tasks:
    - name: Clone API Server repository
      git:
        repo: 'https://github.com/qwer9545/k8s-api-server-base.git'
        dest: '/path/to/destination'
        version: 'main/step05_probono'

    - name: Install Helm
      apt:
        name: helm
        state: present

    - name: Initialize Helm repository
      command: helm repo add stable https://charts.helm.sh/stable
      register: helm_repo_result
      failed_when: "'added' not in helm_repo_result.stdout"

    - name: Package Helm chart
      command: helm package /path/to/destination/k8s/helm-chart
      args:
        chdir: /path/to/destination/k8s/helm-chart
      register: helm_package_result

    - name: Deploy Helm chart
      command: helm install api-server /path/to/destination/k8s/helm-chart/api-server-0.1.0.tgz --namespace api-base
      register: helm_deploy_result
      failed_when: "'deployed' not in helm_deploy_result.stdout"
